#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Create config dir if not present
if [[ ! -d "${PWD}/config" ]]; then
    mkdir -p "${PWD}/config"
    hass --config "${PWD}/config" --script ensure_config
fi

# Create custom_components directory in config if it doesn't exist
mkdir -p "${PWD}/config/custom_components"

# Create symlink to monta integration
if [[ ! -L "${PWD}/config/custom_components/monta" ]]; then
    ln -sf "${PWD}/custom_components/monta" "${PWD}/config/custom_components/monta"
fi

# Start Home Assistant
hass --config "${PWD}/config" --debug
