"""Custom integration to integrate monta with Home Assistant.

For more details about this integration, please refer to
https://github.com/nickknissen/hass-monta
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

from homeassistant.const import CONF_CLIENT_ID, CONF_CLIENT_SECRET, Platform
from homeassistant.core import callback
from homeassistant.helpers import entity_registry as er
from homeassistant.helpers.aiohttp_client import async_get_clientsession
from monta import MontaApiClient

from .const import (
    CONF_SCAN_INTERVAL_CHARGE_POINTS,
    CONF_SCAN_INTERVAL_TRANSACTIONS,
    CONF_SCAN_INTERVAL_WALLET,
    DEFAULT_SCAN_INTERVAL_CHARGE_POINTS,
    DEFAULT_SCAN_INTERVAL_TRANSACTIONS,
    DEFAULT_SCAN_INTERVAL_WALLET,
    DOMAIN,
    LOGGER,
)
from .coordinator import (
    MontaAuthGuard,
    MontaChargePointCoordinator,
    MontaTransactionCoordinator,
    MontaWalletCoordinator,
)
from .entity import account_unique_id
from .services import async_setup_services, async_unload_services
from .storage import (
    HomeAssistantTokenStorage,
    async_get_token_store,
    async_remove_legacy_token_store,
)

if TYPE_CHECKING:
    from homeassistant.config_entries import ConfigEntry
    from homeassistant.core import HomeAssistant

PLATFORMS: list[Platform] = [
    Platform.SENSOR,
    Platform.BINARY_SENSOR,
    Platform.SWITCH,
]


# The account wide sensors used to carry a doubled "monta_", because their
# entity keys were prefixed with the domain as well. Their historical unique
# ids are recorded here, mapped to the key they use today, since the current
# keys can no longer produce them.
LEGACY_ACCOUNT_UNIQUE_IDS = {
    "sensor.monta_monta_wallet_amount": "wallet_amount",
    "sensor.monta_monta_latest_wallet_transactions": "latest_wallet_transactions",
}

# What is left of a legacy charge point unique id once its "<platform>."
# prefix is removed: the numeric charge point id, then the entity key. Ids
# that do not look like this were never generated by this integration, so
# they are left alone rather than pulled into the new namespace.
LEGACY_CHARGE_POINT_SUFFIX = re.compile(r"^\d+_.+$")


@callback
def _async_migrate_unique_ids(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Scope entity unique ids created by earlier versions to this entry.

    Those ids were built with generate_entity_id, so they were entity id
    shaped ("sensor.12345_charge_energy") and shared between config entries.
    Migrating them, rather than letting the entities register under their new
    ids, is what keeps existing entity ids and their history.
    """
    registry = er.async_get(hass)
    for registry_entry in er.async_entries_for_config_entry(registry, entry.entry_id):
        if key := LEGACY_ACCOUNT_UNIQUE_IDS.get(registry_entry.unique_id):
            new_unique_id = account_unique_id(entry.entry_id, key)
        else:
            suffix = registry_entry.unique_id.removeprefix(
                f"{registry_entry.domain}.",
            )
            if suffix == registry_entry.unique_id or not LEGACY_CHARGE_POINT_SUFFIX.match(
                suffix,
            ):
                continue
            new_unique_id = f"{entry.entry_id}_{suffix}"

        try:
            registry.async_update_entity(
                registry_entry.entity_id, new_unique_id=new_unique_id,
            )
        except ValueError:
            # Another entity already claimed the migrated id, which means a
            # leftover from a previous install. Leave it to the user.
            LOGGER.warning(
                "Could not migrate %s to unique id %s because it is already "
                "in use; delete the stale entity to have it recreated",
                registry_entry.entity_id,
                new_unique_id,
            )


# https://developers.home-assistant.io/docs/config_entries_index/#setting-up-an-entry
async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up this integration using UI."""
    hass.data.setdefault(DOMAIN, {})

    _async_migrate_unique_ids(hass, entry)
    await async_remove_legacy_token_store(hass)
    store = async_get_token_store(hass, entry.entry_id)

    scan_interval_charge_points = entry.options.get(
        CONF_SCAN_INTERVAL_CHARGE_POINTS,
        entry.data.get(
            CONF_SCAN_INTERVAL_CHARGE_POINTS, DEFAULT_SCAN_INTERVAL_CHARGE_POINTS,
        ),
    )
    scan_interval_wallet = entry.options.get(
        CONF_SCAN_INTERVAL_WALLET,
        entry.data.get(CONF_SCAN_INTERVAL_WALLET, DEFAULT_SCAN_INTERVAL_WALLET),
    )
    scan_interval_transactions = entry.options.get(
        CONF_SCAN_INTERVAL_TRANSACTIONS,
        entry.data.get(
            CONF_SCAN_INTERVAL_TRANSACTIONS, DEFAULT_SCAN_INTERVAL_TRANSACTIONS,
        ),
    )

    client = MontaApiClient(
        client_id=entry.data[CONF_CLIENT_ID],
        client_secret=entry.data[CONF_CLIENT_SECRET],
        session=async_get_clientsession(hass),
        token_storage=HomeAssistantTokenStorage(store),
    )

    # The coordinators share the client, so they share its tokens and must
    # share the guard that replaces them.
    auth = MontaAuthGuard(client)

    charge_point_coordinator = MontaChargePointCoordinator(
        hass=hass,
        entry=entry,
        client=client,
        auth=auth,
        scan_interval=scan_interval_charge_points,
    )
    wallet_coordinator = MontaWalletCoordinator(
        hass=hass,
        entry=entry,
        client=client,
        auth=auth,
        scan_interval=scan_interval_wallet,
    )
    transaction_coordinator = MontaTransactionCoordinator(
        hass=hass,
        entry=entry,
        client=client,
        auth=auth,
        scan_interval=scan_interval_transactions,
    )

    hass.data[DOMAIN][entry.entry_id] = {
        "charge_point": charge_point_coordinator,
        "wallet": wallet_coordinator,
        "transaction": transaction_coordinator,
    }

    # https://developers.home-assistant.io/docs/integration_fetching_data#coordinated-single-api-poll-for-data-for-all-entities
    await charge_point_coordinator.async_config_entry_first_refresh()
    await wallet_coordinator.async_config_entry_first_refresh()
    await transaction_coordinator.async_config_entry_first_refresh()

    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)

    async_setup_services(hass)

    # No update listener: the config and options flows ask for the reload
    # themselves. Home Assistant deprecated pairing a listener with a flow
    # that reloads, because between them the entry gets set up twice, and two
    # setups mean two clients refreshing the same rotating Monta tokens.

    return True


async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Handle removal of an entry."""
    if unloaded := await hass.config_entries.async_unload_platforms(entry, PLATFORMS):
        hass.data[DOMAIN].pop(entry.entry_id)
        if not hass.data[DOMAIN]:
            # The services are shared by all entries, so they outlive any
            # single one of them.
            async_unload_services(hass)
    return unloaded


async def async_remove_entry(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Discard the entry's cached tokens when the entry is deleted."""
    await async_get_token_store(hass, entry.entry_id).async_remove()
